### ISSUE TITLE
lack of saver and loader model

### ISSUE THREAD

**Issue by guody5** [allenai/pnp#62]
[info] Compiling 50 Scala sources and 2 Java sources to /home/dutang/v-gdy/pnp/target/scala-2.11/classes...
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:15: not found: type Model
[error]     val model: Model, var locallyNormalized: Boolean) {
[error]                ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:501: value addObject is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addObject(config)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:502: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(forwardBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:503: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(backwardBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:504: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(contextBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:505: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(pointerNetInputBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:506: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(pointerNetOutputBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:507: value addObject is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addObject(labelDict)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:682: value loadObject is not a member of edu.cmu.dynet.ModelLoader
[error]     val config = loader.loadObject(classOf[MatchingModelConfig])
[error]                         ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:684: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val forwardLstm = loader.loadLstmBuilder()
[error]                              ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:685: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val backwardLstm = loader.loadLstmBuilder()
[error]                               ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:686: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val contextualBuilder = loader.loadLstmBuilder()
[error]                                    ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:687: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val pointerNetInputBuilder = loader.loadLstmBuilder()
[error]                                         ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:688: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val pointerNetOutputBuilder = loader.loadLstmBuilder()
[error]                                          ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/dqa/matching/MatchingModel.scala:690: value loadObject is not a member of edu.cmu.dynet.ModelLoader
[error]     val labelDict = loader.loadObject(classOf[IndexedList[String]])
[error]                            ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/CompGraph.scala:9: not found: type Model
[error] class CompGraph(val model: Model,
[error]                            ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/CompGraph.scala:23: not found: type Model
[error]   def empty(model: Model): CompGraph = {
[error]                    ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:56: value addBoolean is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addBoolean(locallyNormalized)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:58: value addInt is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addInt(names.size)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:60: value addObject is not a member of edu.cmu.dynet.ModelSaver
[error]       saver.addObject(k)
[error]             ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:64: value addInt is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addInt(lookupNames.size)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:66: value addObject is not a member of edu.cmu.dynet.ModelSaver
[error]       saver.addObject(k)
[error]             ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:74: not found: type Model
[error]     new PnpModel(Map(), Map(), new Model, locallyNormalized)
[error]                                    ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:78: value loadModel is not a member of edu.cmu.dynet.ModelLoader
[error]     val model = loader.loadModel()
[error]                        ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:79: value loadBoolean is not a member of edu.cmu.dynet.ModelLoader
[error]     val locallyNormalized = loader.loadBoolean()
[error]                                    ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:81: value loadInt is not a member of edu.cmu.dynet.ModelLoader
[error]     val numParams = loader.loadInt()
[error]                            ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:84: value loadObject is not a member of edu.cmu.dynet.ModelLoader
[error]       val name = loader.loadObject(classOf[String])
[error]                         ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:85: value loadParameter is not a member of edu.cmu.dynet.ModelLoader
[error]       val param = loader.loadParameter()
[error]                          ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:89: value loadInt is not a member of edu.cmu.dynet.ModelLoader
[error]     val numLookups = loader.loadInt()
[error]                             ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:92: value loadObject is not a member of edu.cmu.dynet.ModelLoader
[error]       val name = loader.loadObject(classOf[String])
[error]                         ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/PnpModel.scala:93: value loadLookupParameter is not a member of edu.cmu.dynet.ModelLoader
[error]       val param = loader.loadLookupParameter()
[error]                          ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:675: value addObject is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addObject(actionSpace)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:676: value addObject is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addObject(vocab)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:677: value addObject is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addObject(config)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:678: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(forwardBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:679: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(backwardBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:680: value addLstmBuilder is not a member of edu.cmu.dynet.ModelSaver
[error]     saver.addLstmBuilder(actionBuilder)
[error]           ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:936: value loadObject is not a member of edu.cmu.dynet.ModelLoader
[error]     val actionSpace = loader.loadObject(classOf[ActionSpace])
[error]                              ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:937: value loadObject is not a member of edu.cmu.dynet.ModelLoader
[error]     val vocab = loader.loadObject(classOf[IndexedList[String]])
[error]                        ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:938: value loadObject is not a member of edu.cmu.dynet.ModelLoader
[error]     val config = loader.loadObject(classOf[SemanticParserConfig])
[error]                         ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:939: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val forwardBuilder = loader.loadLstmBuilder()
[error]                                 ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:940: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val backwardBuilder = loader.loadLstmBuilder()
[error]                                  ^
[error] /home/dutang/v-gdy/pnp/src/main/scala/org/allenai/pnp/semparse/SemanticParser.scala:941: value loadLstmBuilder is not a member of edu.cmu.dynet.ModelLoader
[error]     val actionBuilder = loader.loadLstmBuilder()
[error]                                ^
[warn] Class javax.annotation.CheckReturnValue not found - continuing with a stub.
[warn] Class javax.annotation.CheckReturnValue not found - continuing with a stub.
[warn] Class javax.annotation.CheckReturnValue not found - continuing with a stub.
[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] 5 warnings found
[error] 43 errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 13 s, completed Feb 1, 2018 11:01:06 PM

When I run "sbt test", It seems that version of dynet is wrong, can anyone help me?
I have link dynet_swigJNI_scala.jar and dynet_swigJNI_dylib.jar

**Comment by pdasigi** [comment]
Please make sure you compiled pnp with dynet commit a3149c0f4cd65e663028874a9a9ef1321e05ff8b as stated in the README here: https://github.com/allenai/pnp/tree/wikitables2

**Comment by dungtn** [comment]
git fetch https://github.com/clab/dynet.git a3149c0f4cd65e663028874a9a9ef1321e05ff8b yields error: no such remote ref a3149c0f4cd65e663028874a9a9ef1321e05ff8b

**Comment by pdasigi** [comment]
Looks like the commit does not exist in the original repository anymore. Please use the allenai fork: https://github.com/allenai/dynet for this commit.
