### ISSUE TITLE
Missing data source for wikitables2 experiment

### ISSUE THREAD

**Issue by alexanderkyte** [allenai/pnp#66]
I'm getting an error due to a URL now resolving in a 404. Any chance you have an alternate URL? 

```

~/pnp (wikitables2*) $ ./experiments/wikitables/scripts/download_data.sh  
URL transformed to HTTPS due to an HSTS policy
--2019-01-01 13:07:40--  https://cs.stanford.edu/~ppasupat/research/h-strict-all-matching-lfs.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving cs.stanford.edu (cs.stanford.edu)... 171.64.64.64
Connecting to cs.stanford.edu (cs.stanford.edu)|171.64.64.64|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-01 13:07:41 ERROR 404: Not Found.

```

**Comment by alexanderkyte** [comment]
I see fixtures here: https://github.com/allenai/allennlp/tree/dcd1d25e3f3dd0f672de32403080d75bcfe005b9/allennlp/tests/fixtures/data/wikitables

but I'm not sure what the intended structure of this missing zip files is, so I'm not sure what the correlation between these two sources are.

**Comment by pdasigi** [comment]
Thanks for pointing it out! I've updated the URL in the script.
